# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  setup_config = debug

else ifeq ($(config),release)
  setup_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := setup

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

setup:
ifneq (,$(setup_config))
	@echo "==== Building setup ($(setup_config)) ===="
	@${MAKE} --no-print-directory -C . -f setup.make config=$(setup_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f setup.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   setup"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"